# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x0byourpackage\"\x1c\n\x0bYourRequest\x12\r\n\x05input\x18\x01 \x01(\t\"\x1e\n\x0cYourResponse\x12\x0e\n\x06output\x18\x01 \x01(\t2R\n\x0bYourService\x12\x43\n\nYourMethod\x12\x18.yourpackage.YourRequest\x1a\x19.yourpackage.YourResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_YOURREQUEST']._serialized_start=30
  _globals['_YOURREQUEST']._serialized_end=58
  _globals['_YOURRESPONSE']._serialized_start=60
  _globals['_YOURRESPONSE']._serialized_end=90
  _globals['_YOURSERVICE']._serialized_start=92
  _globals['_YOURSERVICE']._serialized_end=174
# @@protoc_insertion_point(module_scope)
